Repository openshift-cnv/cnv-ci, pull requests merged in 2023-10, with the labels that each got.

#67 Use apply instead of create
  hack/set-imagecontentsourcepolicy.sh
Labels: lgtm, approved, ok-to-test

#68 [4.11 Backport] Use apply instead of create
  hack/set-imagecontentsourcepolicy.sh
Labels: ok-to-test

#69 [4.12 Backport] Use apply instead of create
  hack/set-imagecontentsourcepolicy.sh
Labels: ok-to-test

#70 [4.13 Backport] Use apply instead of create
  hack/set-imagecontentsourcepolicy.sh
Labels: ok-to-test

#75 Sync master with release-4.14
  hack/set-imagecontentsourcepolicy.sh
  version-mapping.json
Labels: approved

#76 Sync master with release-4.15
  hack/set-imagecontentsourcepolicy.sh
  version-mapping.json
Labels: approved

#78 Enable tests for 4.14
  hack/test-cnv.sh
Labels: approved
